### ISSUE TITLE
ember-auto-import : stack: TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by eldk** [eldk/LMW#4]
Use of :
- ember-cli-deploy
- ember-cli-deploy-build
- ember-cli-deploy-git

```
    "ember-cli-deploy": "^1.0.2",
    "ember-cli-deploy-build": "^2.0.0",
    "ember-cli-deploy-git": "^1.3.4",
```

breaks build ( `ember build --environment=production`) and deployment

https://github.com/ef4/ember-cli-deploy-git

https://cli.emberjs.com/release/basic-use/using-addons/

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot read properties of undefined (reading 'length')
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot read properties of undefined (reading 'length')
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot read properties of undefined (reading 'length')
    at ensureTrailingSlash (/home/eldk/SANDBOX/LMW/LMW/node_modules/ember-auto-import/js/package.js:450:17)
    at Package.publicAssetURL (/home/eldk/SANDBOX/LMW/LMW/node_modules/ember-auto-import/js/package.js:269:161)
    at AutoImport.makeBundler (/home/eldk/SANDBOX/LMW/LMW/node_modules/ember-auto-import/js/auto-import.js:107:46)
    at AutoImport.addTo (/home/eldk/SANDBOX/LMW/LMW/node_modules/ember-auto-import/js/auto-import.js:120:51)
    at Class.postprocessTree (/home/eldk/SANDBOX/LMW/LMW/node_modules/ember-auto-import/js/index.js:49:55)
    at /home/eldk/SANDBOX/LMW/LMW/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25
    at Array.reduce (<anonymous>)
    at addonProcessTree (/home/eldk/SANDBOX/LMW/LMW/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/home/eldk/SANDBOX/LMW/LMW/node_modules/ember-cli/lib/broccoli/ember-app.js:935:12)
    at EmberApp.toTree (/home/eldk/SANDBOX/LMW/LMW/node_modules/ember-cli/lib/broccoli/ember-app.js:1758:17)
```

https://github.com/ef4/ember-auto-import/issues/499

**Comment by eldk** [comment]
ember-addon section must be put in ember section :

```
"ember": {
    "edition": "octane",
    "ember-addon": {
      "configPath": "wayto/config",
      "rootURL": "https://user.github.io/repository-name"
    }
  }
```
https://cli.emberjs.com/release/basic-use/using-addons/

**Comment by eldk** [comment]
https://github.com/ef4/ember-cli-deploy-git/issues/35

**Comment by eldk** [comment]
https://github.com/ef4/ember-cli-deploy-git/issues/35
